name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Hatch
      run: pip install hatch

    - name: Build
      run: hatch build

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/*
        if-no-files-found: error

  bundle:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Hatch
      run: pip install hatch

    - name: Bundle
      run: hatch run static:bundle

    - uses: actions/upload-artifact@v3
      with:
        name: bundle
        path: dist/*
        if-no-files-found: error

  publish-pypi:
    runs-on: ubuntu-latest
    environment: pypi
    needs: [build]

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: dist

    #- name: Publish package distributions to PyPI
    #  uses: pypa/gh-action-pypi-publish@release/v1

  publish-github:
    runs-on: ubuntu-latest
    needs: [bundle]

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: bundle
        path: dist

    - name: Publish to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: dist/armaqdl.exe
        draft: true

  publish-windows:
    runs-on: windows-latest
    needs: [publish-github]

    steps:
      # Requires forked winget-pkgs: https://github.com/microsoft/winget-pkgs to the same account as this project
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: jonpas.ArmaQDL
          installers-regex: 'armaqdl.exe'
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }} # Classic Personal Access Token with [public_repo, workflow] scopes
