name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Hatch
      run: pip install hatch

    - name: Build
      run: hatch build

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: dist

    - name: Install Hatch
      run: pip install hatch

    - name: Publish to PyPI
      run: hatch publish
      env:
        HATCH_INDEX_USER: ${{ secrets.HATCH_INDEX_USER }}
        HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
