name: Publish

on:
  release:
    types: [released]

jobs:
  publish-winget:
    runs-on: windows-latest

    steps:
      # Requires forked winget-pkgs: https://github.com/microsoft/winget-pkgs to the same account as this project
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: jonpas.ArmaQDL
          installers-regex: 'armaqdl.exe'
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }} # Classic Personal Access Token with [public_repo, workflow] scopes
