name: Publish

on:
  release:
    types: [released]

jobs:
  publish-winget:
    runs-on: windows-latest
    environment: winget

    steps:
      # Requires forked winget-pkgs: https://github.com/microsoft/winget-pkgs to the same account as this project
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: jonpas.ArmaQDL
          installers-regex: 'armaqdl.exe'
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }} # Classic Personal Access Token with [public_repo, workflow] scopes
