name: Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    name: Python ${{ matrix.python }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Hatch
        run: pip install hatch

      - if: matrix.python == '3.12' && runner.os == 'Linux'
        name: Lint
        run: hatch run lint

      - name: Test
        run: hatch run test
